import type { Product, Category } from "@workspace/api-zod";

export const categories: Category[] = [
  { id: 1, name: "T-Shirts", slug: "t-shirts", description: "Casual and premium tees", createdAt: new Date().toISOString() },
  { id: 2, name: "Hoodies", slug: "hoodies", description: "Comfortable hoodies for every season", createdAt: new Date().toISOString() },
  { id: 3, name: "Pants", slug: "pants", description: "Stylish bottoms", createdAt: new Date().toISOString() },
  { id: 4, name: "Accessories", slug: "accessories", description: "Complete your look", createdAt: new Date().toISOString() },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Classic White Tee",
    slug: "classic-white-tee",
    description: "A timeless white t-shirt crafted from 100% organic cotton. The perfect foundation for any outfit.",
    price: "29.99",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format",
    categoryId: 1,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Gray"],
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Signature Black Hoodie",
    slug: "signature-black-hoodie",
    description: "Our most iconic hoodie. Premium fleece with a relaxed fit and minimal branding.",
    price: "79.99",
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&auto=format",
    categoryId: 2,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Charcoal"],
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Slim Fit Chinos",
    slug: "slim-fit-chinos",
    description: "Versatile chino pants with a modern slim fit. Goes from office to weekend effortlessly.",
    price: "59.99",
    imageUrl: "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=600&auto=format",
    categoryId: 3,
    sizes: ["28x30", "30x30", "32x30", "34x32", "36x32"],
    colors: ["Khaki", "Navy", "Olive"],
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Graphic Logo Tee",
    slug: "graphic-logo-tee",
    description: "Express yourself with our signature graphic tee. Bold design, soft feel.",
    price: "34.99",
    imageUrl: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&auto=format",
    categoryId: 1,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White"],
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Zip-Up Hoodie",
    slug: "zip-up-hoodie",
    description: "A versatile zip-up with a brushed interior for maximum comfort.",
    price: "89.99",
    imageUrl: "https://images.unsplash.com/photo-1542574271-7f3b92e6c821?w=600&auto=format",
    categoryId: 2,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Burgundy"],
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Logo Cap",
    slug: "logo-cap",
    description: "Structured 6-panel cap with embroidered logo. One size fits most.",
    price: "24.99",
    imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format",
    categoryId: 4,
    sizes: ["One Size"],
    colors: ["Black", "White", "Beige"],
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Cargo Pants",
    slug: "cargo-pants",
    description: "Functional cargo pants with a contemporary silhouette and multiple pockets.",
    price: "74.99",
    imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format",
    categoryId: 3,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Olive", "Black", "Stone"],
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Oversized Crew Neck",
    slug: "oversized-crew-neck",
    description: "Dropped shoulders and a relaxed fit make this crew neck an instant favourite.",
    price: "54.99",
    imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format",
    categoryId: 1,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Sage", "Dusty Rose"],
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
];
